### ISSUE TITLE
Clicking on submit button on Add Book page doesnt respond

### ISSUE THREAD

**Issue by Aroniez** [sorakthunly/angular2-node-express-mongo-ngBookStore#1]
I've setup everything well but I cant add books in admin side. There is no response when I click submit button.

**Comment by sorakthunly** [comment]
Thanks, Aroneize. Sorry I haven't been monitoring it often. What's the error message in the console or network tab?

**Comment by Aroniez** [comment]
Hello, 
I noticed the error in my mongo db setup. Thanks

**Comment by abhi3460** [comment]
Hello,
I've setup everything but i can't edit or delete the books and also kindly give me solution for the price of the book, it doesn't store in the database.

thank you
